object_type: global_settings
overrides:
    "xmla.auth.token.enabled": "true"
    "xmla.discover.properties.daxdialect": "tabular"
    "aggregates.create.allowExactDistinctCountMeasures.enabled": "true"
    "aggregates.prediction.checkForNonAdditiveMeasuresAndConstraints.enabled": "false"
    "aggregates.withDistinctCounts.widening.enabled": "true"
    "aggregates.create.withDistinctCounts.queryLevel.enabled": "true"
    "connection.pool.user.idleConnectionDuration": "6 hours"
    "connection.pool.idleConnectionDuration": "6 hours"  
    "query.result.max_rows": "91000" 
    "sml.environment.variables" : 
      LABEL=Postgres
      CONNECTION="dev"
      DB_NAME="ATSCALE_SAMPLE_DATA"
      DB_SCHEMA="as_adventure"
      DB_SCHEMA2="atscale"
      DB_NAME2="atscale_tutorial_data"

